version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: app-db
    environment:
      - MYSQL_ROOT_PASSWORD=welcome*123
      - MYSQL_DATABASE=appdb
    ports:
      - "3306:3306"  
    restart: always

  web:
    image: my-app
    container_name: python-app
    build:
      context: ./app
    environment:
      - HOSTNAME=DockerHost
      - IP_ADDRESS=192.168.225.199
    links:
      - "db"
    restart: always        